load("@rules_python//python:defs.bzl", "py_library")
load("@py_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "quart_sqlalchemy",
    srcs = [
        "__init__.py",
        "_compat.py",
        "model.py",
    ],
)
