---
apiVersion: v1
kind: Pod
metadata:
  name: escape-pulsar
  labels:
    app: escape-pulsar
spec:
  containers:
  - name: escape-pulsar
    image: apachepulsar/pulsar
    ports:
    - containerPort: 6650
    - containerPort: 8080
    command: ["bin/pulsar", "standalone"]
---
apiVersion: v1
kind: Service
metadata:
  name: escape-pulsar
spec:
  selector:
    app: escape-pulsar
  ports:
  - name: pulsar
    protocol: TCP
    port: 6650
    targetPort: 6650
