---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: escape-pulsar
spec:
  selector:
    matchLabels:
      app: escape-pulsar
  replicas: 1
  template:
    metadata:
      labels:
        app: escape-pulsar
    spec:
      containers:
      - name: escape-pulsar
        image: apachepulsar/pulsar
        ports:
        - containerPort: 6650
        - containerPort: 8080
        command: ["bin/pulsar", "standalone"]
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: escape-pulsar
spec:
  selector:
    app: escape-pulsar
  ports:
  - name: pulsar
    protocol: TCP
    port: 6650
    targetPort: 6650
