---
apiVersion: batch/v1
kind: Job
metadata:
  name: escape-backend-init-db
spec:
  activeDeadlineSeconds: 120
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: escape-backend-init-db
        image: localhost:5000/escape_backend:2019-03-24
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: 'mysql+pymysql://raspimgmt:raspberrypi@escape-mariadb/raspimgmt?charset=utf8'
        - name: PULSAR_URL
          value: 'pulsar://escape-pulsar:6650'
        - name: FLASK_APP
          value: app.initdb:initdb
        command: ["python3", "./app/initdb.py"]
        workingDir: "/app"
      restartPolicy: Never
