---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: escape-backend
spec:
  selector:
    matchLabels:
      app: escape-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: escape-backend
    spec:
      containers:
      - name: escape-backend
        image: registry.houdini.traber-web.ch:5000/escape_backend:2019-09-10
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: 'mysql+pymysql://raspimgmt:raspberrypi@escape-mariadb/raspimgmt?charset=utf8'
        - name: PULSAR_URL
          value: 'pulsar://escape-pulsar:6650'
        - name: MINIO_URL
          value: 'localhost:9000'
        - name: MINIO_ACCESS_KEY
          value: 'L8Adf/ADnAglARAvA015'
        - name: MINIO_SECRET_KEY
          value: 'fA9hJAKFmnwsd/SDMASFA/Ljlkdfg239563ADSGA'
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: escape-backend
spec:
  selector:
    app: escape-backend
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
