version: '3'
services:
  escape-tftp:
    build: ./tftp/
    restart: unless-stopped
    volumes:
      - ./tftp/data:/var/tftpboot
    network_mode: host
  escape-nfs:
    build: ./nfs/
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nfs/data:/data
        #    ports:
        #      - "111:111/udp"
        #      - "111:111/tcp"
        #      - "2049:2049/udp"
        #      - "2049:2049/tcp"
