- hosts: raspis
  user: pi
  become_user: root
  become_method: sudo
  tasks:
    - name: Install OS dependencies
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: git,python3-venv
        state: present

    - name: Checkout github repository
      git: repo='https://github.com/atraber/escapemgmt.git' dest=/home/pi/escapemgmt version=master

    - name: Create virtualenv
      pip:
        requirements: /home/pi/escapemgmt/raspi-streamer/requirements.txt
        virtualenv: /home/pi/escapemgmt/raspi-streamer/venv
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Create autostart entry
      copy:
        dest: "/home/pi/.config/autostart/stream.desktop"
        content: |
          [Desktop Entry]
          Encoding=UTF-8
          Name=stream
          GenericName=stream
          Exec=/home/pi/escapemgmt/raspi-streamer/start.sh
          Terminal=false
          Type=Application
          Categories=

    - name: Restart server
      become: true
      command: reboot
      async: 0
      poll: 0
      ignore_errors: true
