- hosts: raspis
  user: pi
  become_user: root
  become_method: sudo
  tasks:
    - name: Run XFCE update playbook
      include_tasks: raspi-xfce.yaml

    - name: Run docker install playbook
      include_tasks: raspi-docker-install.yaml

    - name: Run docker update playbook
      include_tasks: raspi-docker-update.yaml

    - name: Restart server
      become: true
      command: reboot
      async: 0
      poll: 0
      ignore_errors: true
