- hosts: raspis
  user: pi
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Stop docker-compose
      become: true
      command: docker-compose -f /home/pi/docker-compose.rpi.yml down
      ignore_errors: yes

    - name: Update docker-compose file
      copy:
        dest: "/home/pi/docker-compose.rpi.yml"
        content: |
          version: '3'
          services:
            streamer:
              image: 192.168.0.150:5000/escape_streamer:2019-03-24
              ports:
                - "8081:8081"
              restart: always
              environment:
                - DISPLAY=:0
              healthcheck:
                  test: ["CMD", "python3", "-u", "/app/health_check_client.py"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
              network_mode: "host"
              devices:
                - "/dev/vchiq:/dev/vchiq"
                - "/dev/snd:/dev/snd"
                - "/dev/fb0:/dev/fb0"
              volumes:
                - /tmp/.X11-unix:/tmp/.X11-unix
                - /home/pi/.Xauthority:/root/.Xauthority
                - /home/pi/config.yml:/app/config.yml

    - name: Pull docker-compose
      become: true
      command: docker-compose -f /home/pi/docker-compose.rpi.yml pull

    - name: Start docker-compose
      become: true
      command: docker-compose -f /home/pi/docker-compose.rpi.yml up -d
