- hosts: raspis
  user: pi
  tasks:
    - name: Install git
      become: true
      become_user: root
      become_method: sudo
      apt: name=git state=present

    - name: Checkout github repository
      git: repo='https://github.com/atraber/escapemgmt.git' dest=/home/pi/escapemgmt version=master

    - name: Create autostart entry
      copy:
        dest: "/home/pi/.config/autostart/stream.desktop"
        content: |
          [Desktop Entry]
          Encoding=UTF-8
          Name=stream
          GenericName=stream
          Exec=/home/pi/escapemgmt/raspi-streamer/main.py
          Terminal=false
          Type=Application
          Categories=
