- hosts: tv
  user: pi
  become_user: root
  become_method: sudo

  tasks:
    - name: Install git
      become: true
      apt: name=git state=present

    - name: Checkout github repository
      git: repo='https://github.com/atraber/escapemgmt.git' dest=/home/pi/escapemgmt version=master

    - name: Create autostart entry
      copy:
        dest: "/home/pi/autostart.sh"
        content: |
          xset s off
          xset s noblank
          xset -dpms
          iceweasel http://192.168.0.150/frontscreen &
          sleep 2
          xdotool search --sync --onlyvisible --class "Firefox" windowactivate key F11
          sleep 10
          xdotool search --sync --onlyvisible --class "Firefox" windowactivate key ctrl+F5
          unclutter -idle 2.00 -root &


    - name: Create firefox refresh
      copy:
        dest: "/home/pi/firefox_refresh.sh"
        content: |
          export DISPLAY=:0
          xdotool search --sync --onlyvisible --class "Firefox" windowactivate key ctrl+F5

    - name: Create firefox refresh
      copy:
        dest: "/home/pi/.config/autostart/autostart.desktop"
        content: |
         [Desktop Entry]
          Encoding=UTF-8
          Name=stream
          GenericName=iceweasel
          Exec=/home/pi/autostart.sh
          Terminal=false
          Type=Application
          Categories=

    - name: Wallpaper
      copy:
        src: ./raspi/desktop.jpg
        dest: ~/desktop.jpg

    - name: XFCE Config
      copy:
        src: ./raspi/xfce-session.cfg
        dest: ~/.cache/sessions/xfce4-session-raspberrypi:0

    - name: XFCE Desktop Config
      copy:
        src: ./raspi/xfce4-desktop.xml
        dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

    - name: XFCE Panel Config
      copy:
        src: ./raspi/xfce4-panel.xml
        dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml

    - name: Splash Screen Cmdline Settings
      become: true
      copy:
        dest: "/boot/cmdline.txt"
        content: |
         dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=5ade1fc3-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash logo.nologo

    - name: Restart server
      become: true
      command: reboot
      async: 0
      poll: 0
      ignore_errors: true
