"""empty message

Revision ID: c1cfeb3e688e
Revises: 65aca1009bd4
Create Date: 2018-06-08 16:24:55.648429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1cfeb3e688e'
down_revision = '65aca1009bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('crop_x1', sa.Integer(), nullable=False))
    op.add_column('streams', sa.Column('crop_y1', sa.Integer(), nullable=False))
    op.alter_column('streams', 'width', new_column_name='crop_x2', existing_type=sa.Integer(), nullable=False)
    op.alter_column('streams', 'height', new_column_name='crop_y2', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'crop_y1')
    op.drop_column('streams', 'crop_x1')
    op.alter_column('streams', 'crop_x2', new_column_name='width', existing_type=sa.Integer())
    op.alter_column('streams', 'crop_y2', new_column_name='height', existing_type=sa.Integer())
    # ### end Alembic commands ###
